POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "abc",
  "password": "abc@123"
}
###

POST http://localhost:3000/
Content-Type: application/json


{
    "userId": 2,
    "id": 3,
    "title": "css",
    "body":"react,html,css"
  }


###

GET http://localhost:3000/posts/


###

GET http://localhost:3000/posts/1
###